2019-09-17T16:37:16.8083096+01:00 0HLPRGJLL3DHH:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:51933/api/values   (ca22a1cb)
2019-09-17T16:37:17.9163153+01:00 0HLPRGJLL3DHH:00000001 [INF] Route matched with "{action = \"Get\", controller = \"Values\"}". Executing action "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)" (a44c0341)
2019-09-17T16:37:18.0394292+01:00 0HLPRGJLL3DHH:00000001 [INF] Executing action method "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)" - Validation state: Valid (dad538d7)
2019-09-17T16:37:18.0614137+01:00 0HLPRGJLL3DHH:00000001 [INF] Executed action method "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)", returned result "Microsoft.AspNetCore.Mvc.ObjectResult" in 7.283ms. (50a9e262)
2019-09-17T16:37:18.1294185+01:00 0HLPRGJLL3DHH:00000001 [INF] Executing ObjectResult, writing value of type '"System.String[]"'. (8a1b66c8)
2019-09-17T16:37:18.3383631+01:00 0HLPRGJLL3DHH:00000001 [INF] Executed action "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)" in 405.8996ms (afa2e885)
2019-09-17T16:37:18.3635292+01:00 0HLPRGJLL3DHH:00000001 [INF] Request finished in 1617.7497ms 200 application/json; charset=utf-8 (791a596a)
2019-09-17T16:37:18.4125612+01:00 0HLPRGJLL3DHH:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:51933/favicon.ico   (ca22a1cb)
2019-09-17T16:37:18.4802124+01:00 0HLPRGJLL3DHH:00000002 [INF] Request finished in 67.9657ms 404  (791a596a)
2019-09-17T16:37:30.1058811+01:00 0HLPRGJLL3DHH:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:51933/api/person   (ca22a1cb)
2019-09-17T16:37:30.1172790+01:00 0HLPRGJLL3DHH:00000003 [INF] Route matched with "{action = \"Get\", controller = \"Person\"}". Executing action "GFut.Services.Api.Controllers.PersonController.Get (GFut.Services.Api)" (a44c0341)
2019-09-17T16:37:30.1279560+01:00 0HLPRGJLL3DHH:00000003 [INF] Executed action "GFut.Services.Api.Controllers.PersonController.Get (GFut.Services.Api)" in 6.9447ms (afa2e885)
2019-09-17T16:37:30.3328790+01:00 0HLPRGJLL3DHH:00000003 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.InvalidOperationException: Unable to resolve service for type 'AutoMapper.IMapper' while attempting to activate 'GFut.Application.Services.PersonAppService'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2019-09-17T16:37:30.5896556+01:00 0HLPRGJLL3DHH:00000003 [INF] Request finished in 479.257ms 500 text/html; charset=utf-8 (791a596a)
2019-09-17T17:16:19.4614136+01:00 0HLPRH9FPTE72:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:51933/api/values   (ca22a1cb)
2019-09-17T17:16:20.1568296+01:00 0HLPRH9FPTE72:00000001 [INF] Route matched with "{action = \"Get\", controller = \"Values\"}". Executing action "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)" (a44c0341)
2019-09-17T17:16:20.2438886+01:00 0HLPRH9FPTE72:00000001 [INF] Executing action method "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)" - Validation state: Valid (dad538d7)
2019-09-17T17:16:20.2564299+01:00 0HLPRH9FPTE72:00000001 [INF] Executed action method "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)", returned result "Microsoft.AspNetCore.Mvc.ObjectResult" in 2.6041ms. (50a9e262)
2019-09-17T17:16:20.3130305+01:00 0HLPRH9FPTE72:00000001 [INF] Executing ObjectResult, writing value of type '"System.String[]"'. (8a1b66c8)
2019-09-17T17:16:20.6301706+01:00 0HLPRH9FPTE72:00000001 [INF] Executed action "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)" in 452.8019ms (afa2e885)
2019-09-17T17:16:20.6510404+01:00 0HLPRH9FPTE72:00000001 [INF] Request finished in 1265.8888ms 200 application/json; charset=utf-8 (791a596a)
2019-09-17T17:16:20.7126609+01:00 0HLPRH9FPTE72:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:51933/favicon.ico   (ca22a1cb)
2019-09-17T17:16:20.8073895+01:00 0HLPRH9FPTE72:00000002 [INF] Request finished in 94.9391ms 404  (791a596a)
2019-09-17T17:16:33.3270950+01:00 0HLPRH9FPTE72:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:51933/api/person   (ca22a1cb)
2019-09-17T17:16:33.3457748+01:00 0HLPRH9FPTE72:00000003 [INF] Route matched with "{action = \"Get\", controller = \"Person\"}". Executing action "GFut.Services.Api.Controllers.PersonController.Get (GFut.Services.Api)" (a44c0341)
2019-09-17T17:16:33.3552870+01:00 0HLPRH9FPTE72:00000003 [INF] Executed action "GFut.Services.Api.Controllers.PersonController.Get (GFut.Services.Api)" in 6.0229ms (afa2e885)
2019-09-17T17:16:33.5551607+01:00 0HLPRH9FPTE72:00000003 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.InvalidOperationException: Unable to resolve service for type 'GFut.Infra.Data.Context.AppDbContext' while attempting to activate 'GFut.Infra.Data.Repository.PersonRepository'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2019-09-17T17:16:33.8247011+01:00 0HLPRH9FPTE72:00000003 [INF] Request finished in 501.1173ms 500 text/html; charset=utf-8 (791a596a)
2019-09-17T17:20:18.6485720+01:00 0HLPRHBN3JA1I:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:51933/api/values   (ca22a1cb)
2019-09-17T17:20:19.3836329+01:00 0HLPRHBN3JA1I:00000001 [INF] Route matched with "{action = \"Get\", controller = \"Values\"}". Executing action "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)" (a44c0341)
2019-09-17T17:20:19.4878010+01:00 0HLPRHBN3JA1I:00000001 [INF] Executing action method "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)" - Validation state: Valid (dad538d7)
2019-09-17T17:20:19.4975011+01:00 0HLPRHBN3JA1I:00000001 [INF] Executed action method "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)", returned result "Microsoft.AspNetCore.Mvc.ObjectResult" in 1.9827ms. (50a9e262)
2019-09-17T17:20:19.5413365+01:00 0HLPRHBN3JA1I:00000001 [INF] Executing ObjectResult, writing value of type '"System.String[]"'. (8a1b66c8)
2019-09-17T17:20:19.7938037+01:00 0HLPRHBN3JA1I:00000001 [INF] Executed action "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)" in 395.7591ms (afa2e885)
2019-09-17T17:20:19.8297117+01:00 0HLPRHBN3JA1I:00000001 [INF] Request finished in 1217.105ms 200 application/json; charset=utf-8 (791a596a)
2019-09-17T17:20:19.8976615+01:00 0HLPRHBN3JA1I:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:51933/favicon.ico   (ca22a1cb)
2019-09-17T17:20:19.9569320+01:00 0HLPRHBN3JA1I:00000002 [INF] Request finished in 61.5121ms 404  (791a596a)
2019-09-17T17:20:28.1895265+01:00 0HLPRHBN3JA1I:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:51933/api/person   (ca22a1cb)
2019-09-17T17:20:28.2010186+01:00 0HLPRHBN3JA1I:00000003 [INF] Route matched with "{action = \"Get\", controller = \"Person\"}". Executing action "GFut.Services.Api.Controllers.PersonController.Get (GFut.Services.Api)" (a44c0341)
2019-09-17T17:20:28.2077818+01:00 0HLPRHBN3JA1I:00000003 [INF] Executed action "GFut.Services.Api.Controllers.PersonController.Get (GFut.Services.Api)" in 3.6655ms (afa2e885)
2019-09-17T17:20:28.4259833+01:00 0HLPRHBN3JA1I:00000003 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.InvalidOperationException: Unable to resolve service for type 'GFut.Infra.Data.Context.AppDbContext' while attempting to activate 'GFut.Infra.Data.Repository.PersonRepository'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2019-09-17T17:20:28.7898069+01:00 0HLPRHBN3JA1I:00000003 [INF] Request finished in 562.3915ms 500 text/html; charset=utf-8 (791a596a)
2019-09-17T17:32:32.8546426+01:00 0HLPRHIHSHDQ2:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:51933/api/values   (ca22a1cb)
2019-09-17T17:32:33.9454820+01:00 0HLPRHIHSHDQ2:00000001 [INF] Route matched with "{action = \"Get\", controller = \"Values\"}". Executing action "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)" (a44c0341)
2019-09-17T17:32:34.0669131+01:00 0HLPRHIHSHDQ2:00000001 [INF] Executing action method "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)" - Validation state: Valid (dad538d7)
2019-09-17T17:32:34.0912516+01:00 0HLPRHIHSHDQ2:00000001 [INF] Executed action method "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)", returned result "Microsoft.AspNetCore.Mvc.ObjectResult" in 3.9188ms. (50a9e262)
2019-09-17T17:32:34.1819402+01:00 0HLPRHIHSHDQ2:00000001 [INF] Executing ObjectResult, writing value of type '"System.String[]"'. (8a1b66c8)
2019-09-17T17:32:34.7813511+01:00 0HLPRHIHSHDQ2:00000001 [INF] Executed action "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)" in 799.5024ms (afa2e885)
2019-09-17T17:32:34.8270585+01:00 0HLPRHIHSHDQ2:00000001 [INF] Request finished in 2052.6121ms 200 application/json; charset=utf-8 (791a596a)
2019-09-17T17:32:34.8776642+01:00 0HLPRHIHSHDQ2:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:51933/favicon.ico   (ca22a1cb)
2019-09-17T17:32:35.0153400+01:00 0HLPRHIHSHDQ2:00000002 [INF] Request finished in 133.5329ms 404  (791a596a)
2019-09-17T17:33:08.4773834+01:00 0HLPRHIHSHDQ2:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:51933/api/person   (ca22a1cb)
2019-09-17T17:33:08.4964795+01:00 0HLPRHIHSHDQ2:00000003 [INF] Route matched with "{action = \"Get\", controller = \"Person\"}". Executing action "GFut.Services.Api.Controllers.PersonController.Get (GFut.Services.Api)" (a44c0341)
2019-09-17T17:33:13.7288416+01:00 0HLPRHIHSHDQ2:00000003 [INF] Executed action "GFut.Services.Api.Controllers.PersonController.Get (GFut.Services.Api)" in 5227.5031ms (afa2e885)
2019-09-17T17:33:14.0364719+01:00 0HLPRHIHSHDQ2:00000003 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.ArgumentNullException: Value cannot be null.
Parameter name: connectionString
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotEmpty(String value, String parameterName)
   at Microsoft.EntityFrameworkCore.SqlServerDbContextOptionsExtensions.UseSqlServer(DbContextOptionsBuilder optionsBuilder, String connectionString, Action`1 sqlServerOptionsAction)
   at GFut.Infra.Data.Context.AppDbContext.OnConfiguring(DbContextOptionsBuilder optionsBuilder) in c:\users\gesse\source\repos\GFut\GFut.Infra\Context\AppDbContext.cs:line 33
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at GFut.Infra.Data.Repository.Repository`1..ctor(AppDbContext context) in c:\users\gesse\source\repos\GFut\GFut.Infra\Repository\Repository.cs:line 17
   at GFut.Infra.Data.Repository.PersonRepository..ctor(AppDbContext context) in c:\users\gesse\source\repos\GFut\GFut.Infra\Repository\PersonRepository.cs:line 14
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2019-09-17T17:33:14.3799982+01:00 0HLPRHIHSHDQ2:00000003 [INF] Request finished in 5881.1828ms 500 text/html; charset=utf-8 (791a596a)
2019-09-17T17:34:57.1853813+01:00 0HLPRHJSSNE4A:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:51933/api/values   (ca22a1cb)
2019-09-17T17:34:58.1919454+01:00 0HLPRHJSSNE4A:00000001 [INF] Route matched with "{action = \"Get\", controller = \"Values\"}". Executing action "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)" (a44c0341)
2019-09-17T17:34:58.3585527+01:00 0HLPRHJSSNE4A:00000001 [INF] Executing action method "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)" - Validation state: Valid (dad538d7)
2019-09-17T17:34:58.3910643+01:00 0HLPRHJSSNE4A:00000001 [INF] Executed action method "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)", returned result "Microsoft.AspNetCore.Mvc.ObjectResult" in 3.6725ms. (50a9e262)
2019-09-17T17:34:58.5167535+01:00 0HLPRHJSSNE4A:00000001 [INF] Executing ObjectResult, writing value of type '"System.String[]"'. (8a1b66c8)
2019-09-17T17:34:59.0214496+01:00 0HLPRHJSSNE4A:00000001 [INF] Executed action "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)" in 760.9012ms (afa2e885)
2019-09-17T17:34:59.1608548+01:00 0HLPRHJSSNE4A:00000001 [INF] Request finished in 2028.3095ms 200 application/json; charset=utf-8 (791a596a)
2019-09-17T17:34:59.2197008+01:00 0HLPRHJSSNE4A:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:51933/favicon.ico   (ca22a1cb)
2019-09-17T17:34:59.3304105+01:00 0HLPRHJSSNE4A:00000002 [INF] Request finished in 110.4909ms 404  (791a596a)
2019-09-17T17:35:07.0379327+01:00 0HLPRHJSSNE4A:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:51933/api/person   (ca22a1cb)
2019-09-17T17:35:07.0693732+01:00 0HLPRHJSSNE4A:00000003 [INF] Route matched with "{action = \"Get\", controller = \"Person\"}". Executing action "GFut.Services.Api.Controllers.PersonController.Get (GFut.Services.Api)" (a44c0341)
2019-09-17T17:35:09.6426648+01:00 0HLPRHJSSNE4A:00000003 [INF] Executing action method "GFut.Services.Api.Controllers.PersonController.Get (GFut.Services.Api)" - Validation state: Valid (dad538d7)
2019-09-17T17:38:45.5882733+01:00 0HLPRHJSSNE4A:00000003 [INF] Executed action "GFut.Services.Api.Controllers.PersonController.Get (GFut.Services.Api)" in 218494.3554ms (afa2e885)
2019-09-17T17:38:45.8589805+01:00 0HLPRHJSSNE4A:00000003 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.NullReferenceException: Object reference not set to an instance of an object.
   at GFut.Application.Services.PersonAppService.GetAll() in c:\users\gesse\source\repos\GFut\GFut.Application\Services\PersonAppService.cs:line 24
   at GFut.Services.Api.Controllers.PersonController.Get() in c:\users\gesse\source\repos\GFut\GFut.Services.Api\Controllers\PersonController.cs:line 24
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2019-09-17T17:38:46.1784939+01:00 0HLPRHJSSNE4A:00000003 [INF] Request finished in 219120.1173ms 500 text/html; charset=utf-8 (791a596a)
2019-09-17T17:40:22.1892246+01:00 0HLPRHMTNUKLB:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:51933/api/values   (ca22a1cb)
2019-09-17T17:40:23.5626462+01:00 0HLPRHMTNUKLB:00000001 [INF] Route matched with "{action = \"Get\", controller = \"Values\"}". Executing action "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)" (a44c0341)
2019-09-17T17:40:23.7431790+01:00 0HLPRHMTNUKLB:00000001 [INF] Executing action method "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)" - Validation state: Valid (dad538d7)
2019-09-17T17:40:23.7781698+01:00 0HLPRHMTNUKLB:00000001 [INF] Executed action method "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)", returned result "Microsoft.AspNetCore.Mvc.ObjectResult" in 3.6524ms. (50a9e262)
2019-09-17T17:40:23.8940884+01:00 0HLPRHMTNUKLB:00000001 [INF] Executing ObjectResult, writing value of type '"System.String[]"'. (8a1b66c8)
2019-09-17T17:40:24.3865497+01:00 0HLPRHMTNUKLB:00000001 [INF] Executed action "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)" in 772.0051ms (afa2e885)
2019-09-17T17:40:24.4490706+01:00 0HLPRHMTNUKLB:00000001 [INF] Request finished in 2398.5252ms 200 application/json; charset=utf-8 (791a596a)
2019-09-17T17:40:24.5572078+01:00 0HLPRHMTNUKLB:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:51933/favicon.ico   (ca22a1cb)
2019-09-17T17:40:24.6754446+01:00 0HLPRHMTNUKLB:00000002 [INF] Request finished in 154.2371ms 404  (791a596a)
2019-09-17T17:42:09.8995170+01:00 0HLPRHMTNUKLD:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:51933/api/person   (ca22a1cb)
2019-09-17T17:42:09.9229364+01:00 0HLPRHMTNUKLD:00000001 [INF] Route matched with "{action = \"Get\", controller = \"Person\"}". Executing action "GFut.Services.Api.Controllers.PersonController.Get (GFut.Services.Api)" (a44c0341)
2019-09-17T17:42:12.2540272+01:00 0HLPRHMTNUKLD:00000001 [INF] Executing action method "GFut.Services.Api.Controllers.PersonController.Get (GFut.Services.Api)" - Validation state: Valid (dad538d7)
2019-09-17T17:43:59.9646019+01:00 0HLPRHOUKKR8J:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:51933/api/values   (ca22a1cb)
2019-09-17T17:44:01.1700292+01:00 0HLPRHOUKKR8J:00000001 [INF] Route matched with "{action = \"Get\", controller = \"Values\"}". Executing action "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)" (a44c0341)
2019-09-17T17:44:01.3037856+01:00 0HLPRHOUKKR8J:00000001 [INF] Executing action method "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)" - Validation state: Valid (dad538d7)
2019-09-17T17:44:01.3338764+01:00 0HLPRHOUKKR8J:00000001 [INF] Executed action method "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)", returned result "Microsoft.AspNetCore.Mvc.ObjectResult" in 3.7779ms. (50a9e262)
2019-09-17T17:44:01.4610273+01:00 0HLPRHOUKKR8J:00000001 [INF] Executing ObjectResult, writing value of type '"System.String[]"'. (8a1b66c8)
2019-09-17T17:44:02.0564614+01:00 0HLPRHOUKKR8J:00000001 [INF] Executed action "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)" in 767.8753ms (afa2e885)
2019-09-17T17:44:02.1420172+01:00 0HLPRHOUKKR8J:00000001 [INF] Request finished in 2267.9295ms 200 application/json; charset=utf-8 (791a596a)
2019-09-17T17:44:02.1862322+01:00 0HLPRHOUKKR8J:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:51933/favicon.ico   (ca22a1cb)
2019-09-17T17:44:02.3126344+01:00 0HLPRHOUKKR8J:00000002 [INF] Request finished in 109.5401ms 404  (791a596a)
2019-09-17T17:44:06.7336282+01:00 0HLPRHOUKKR8J:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:51933/api/person   (ca22a1cb)
2019-09-17T17:44:06.7587401+01:00 0HLPRHOUKKR8J:00000003 [INF] Route matched with "{action = \"Get\", controller = \"Person\"}". Executing action "GFut.Services.Api.Controllers.PersonController.Get (GFut.Services.Api)" (a44c0341)
2019-09-17T17:44:09.5413406+01:00 0HLPRHOUKKR8J:00000003 [INF] Executing action method "GFut.Services.Api.Controllers.PersonController.Get (GFut.Services.Api)" - Validation state: Valid (dad538d7)
2019-09-17T17:44:09.6630727+01:00 0HLPRHOUKKR8J:00000003 [INF] Executed action method "GFut.Services.Api.Controllers.PersonController.Get (GFut.Services.Api)", returned result "Microsoft.AspNetCore.Mvc.ObjectResult" in 105.1496ms. (50a9e262)
2019-09-17T17:44:09.6988585+01:00 0HLPRHOUKKR8J:00000003 [INF] Executing ObjectResult, writing value of type '"Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[[GFut.Application.ViewModels.PersonViewModel, GFut.Application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"'. (8a1b66c8)
2019-09-17T17:44:09.8369798+01:00 0HLPRHOUKKR8J:00000003 [INF] Executed action "GFut.Services.Api.Controllers.PersonController.Get (GFut.Services.Api)" in 3059.9973ms (afa2e885)
2019-09-17T17:44:10.1567200+01:00 0HLPRHOUKKR8J:00000003 [ERR] An unhandled exception has occurred while executing the request (cf926119)
Newtonsoft.Json.JsonSerializationException: A member with the name 'email' already exists on 'GFut.Application.ViewModels.PersonViewModel'. Use the JsonPropertyAttribute to specify another name.
   at Newtonsoft.Json.Serialization.JsonPropertyCollection.AddProperty(JsonProperty property)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperties(Type type, MemberSerialization memberSerialization)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteStartArray(JsonWriter writer, Object values, JsonArrayContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.WriteObject(TextWriter writer, Object value)
   at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.<WriteResponseBodyAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__28`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultFilters>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2019-09-17T17:44:10.5306701+01:00 0HLPRHOUKKR8J:00000003 [INF] Request finished in 3783.5251ms 500 text/html; charset=utf-8 (791a596a)
2019-09-17T17:47:04.3347465+01:00 0HLPRHQLJK978:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:51933/api/values   (ca22a1cb)
2019-09-17T17:47:05.3769424+01:00 0HLPRHQLJK978:00000001 [INF] Route matched with "{action = \"Get\", controller = \"Values\"}". Executing action "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)" (a44c0341)
2019-09-17T17:47:05.4859741+01:00 0HLPRHQLJK978:00000001 [INF] Executing action method "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)" - Validation state: Valid (dad538d7)
2019-09-17T17:47:05.5124852+01:00 0HLPRHQLJK978:00000001 [INF] Executed action method "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)", returned result "Microsoft.AspNetCore.Mvc.ObjectResult" in 3.4793ms. (50a9e262)
2019-09-17T17:47:05.5967245+01:00 0HLPRHQLJK978:00000001 [INF] Executing ObjectResult, writing value of type '"System.String[]"'. (8a1b66c8)
2019-09-17T17:47:05.9998936+01:00 0HLPRHQLJK978:00000001 [INF] Executed action "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)" in 581.6364ms (afa2e885)
2019-09-17T17:47:06.0645277+01:00 0HLPRHQLJK978:00000001 [INF] Request finished in 1801.6233ms 200 application/json; charset=utf-8 (791a596a)
2019-09-17T17:47:06.1181046+01:00 0HLPRHQLJK978:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:51933/favicon.ico   (ca22a1cb)
2019-09-17T17:47:06.2085413+01:00 0HLPRHQLJK978:00000002 [INF] Request finished in 90.5626ms 404  (791a596a)
2019-09-17T17:47:23.7894048+01:00 0HLPRHQLJK978:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:51933/api/person   (ca22a1cb)
2019-09-17T17:47:23.8203200+01:00 0HLPRHQLJK978:00000003 [INF] Route matched with "{action = \"Get\", controller = \"Person\"}". Executing action "GFut.Services.Api.Controllers.PersonController.Get (GFut.Services.Api)" (a44c0341)
2019-09-17T17:47:26.2618253+01:00 0HLPRHQLJK978:00000003 [INF] Executing action method "GFut.Services.Api.Controllers.PersonController.Get (GFut.Services.Api)" - Validation state: Valid (dad538d7)
2019-09-17T17:47:26.3633412+01:00 0HLPRHQLJK978:00000003 [INF] Executed action method "GFut.Services.Api.Controllers.PersonController.Get (GFut.Services.Api)", returned result "Microsoft.AspNetCore.Mvc.ObjectResult" in 82.3507ms. (50a9e262)
2019-09-17T17:47:26.4007533+01:00 0HLPRHQLJK978:00000003 [INF] Executing ObjectResult, writing value of type '"Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[[GFut.Application.ViewModels.PersonViewModel, GFut.Application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"'. (8a1b66c8)
2019-09-17T17:47:26.5073300+01:00 0HLPRHQLJK978:00000003 [INF] Executed action "GFut.Services.Api.Controllers.PersonController.Get (GFut.Services.Api)" in 2672.9329ms (afa2e885)
2019-09-17T17:47:26.8030195+01:00 0HLPRHQLJK978:00000003 [ERR] An unhandled exception has occurred while executing the request (cf926119)
Newtonsoft.Json.JsonSerializationException: A member with the name 'email' already exists on 'GFut.Application.ViewModels.PersonViewModel'. Use the JsonPropertyAttribute to specify another name.
   at Newtonsoft.Json.Serialization.JsonPropertyCollection.AddProperty(JsonProperty property)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperties(Type type, MemberSerialization memberSerialization)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteStartArray(JsonWriter writer, Object values, JsonArrayContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.WriteObject(TextWriter writer, Object value)
   at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.<WriteResponseBodyAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__28`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultFilters>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2019-09-17T17:47:27.1514038+01:00 0HLPRHQLJK978:00000003 [INF] Request finished in 3355.7158ms 500 text/html; charset=utf-8 (791a596a)
2019-09-17T18:15:38.2263418+01:00 0HLPRIAKCIC7F:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:51933/api/values   (ca22a1cb)
2019-09-17T18:15:39.2911552+01:00 0HLPRIAKCIC7F:00000001 [INF] Route matched with "{action = \"Get\", controller = \"Values\"}". Executing action "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)" (a44c0341)
2019-09-17T18:15:39.4196286+01:00 0HLPRIAKCIC7F:00000001 [INF] Executing action method "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)" - Validation state: Valid (dad538d7)
2019-09-17T18:15:39.4485494+01:00 0HLPRIAKCIC7F:00000001 [INF] Executed action method "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)", returned result "Microsoft.AspNetCore.Mvc.ObjectResult" in 4.2524ms. (50a9e262)
2019-09-17T18:15:39.5432810+01:00 0HLPRIAKCIC7F:00000001 [INF] Executing ObjectResult, writing value of type '"System.String[]"'. (8a1b66c8)
2019-09-17T18:15:39.9475879+01:00 0HLPRIAKCIC7F:00000001 [INF] Executed action "GFut.Services.Api.Controllers.ValuesController.Get (GFut.Services.Api)" in 619.5463ms (afa2e885)
2019-09-17T18:15:40.0249090+01:00 0HLPRIAKCIC7F:00000001 [INF] Request finished in 1848.415ms 200 application/json; charset=utf-8 (791a596a)
2019-09-17T18:15:40.0794287+01:00 0HLPRIAKCIC7F:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:51933/favicon.ico   (ca22a1cb)
2019-09-17T18:15:40.1678561+01:00 0HLPRIAKCIC7F:00000002 [INF] Request finished in 86.9134ms 404  (791a596a)
2019-09-17T18:15:46.3841900+01:00 0HLPRIAKCIC7F:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:51933/api/person   (ca22a1cb)
2019-09-17T18:15:46.4112241+01:00 0HLPRIAKCIC7F:00000003 [INF] Route matched with "{action = \"Get\", controller = \"Person\"}". Executing action "GFut.Services.Api.Controllers.PersonController.Get (GFut.Services.Api)" (a44c0341)
2019-09-17T18:15:48.5413607+01:00 0HLPRIAKCIC7F:00000003 [INF] Executing action method "GFut.Services.Api.Controllers.PersonController.Get (GFut.Services.Api)" - Validation state: Valid (dad538d7)
2019-09-17T18:15:48.6283698+01:00 0HLPRIAKCIC7F:00000003 [INF] Executed action method "GFut.Services.Api.Controllers.PersonController.Get (GFut.Services.Api)", returned result "Microsoft.AspNetCore.Mvc.ObjectResult" in 66.8922ms. (50a9e262)
2019-09-17T18:15:48.6534561+01:00 0HLPRIAKCIC7F:00000003 [INF] Executing ObjectResult, writing value of type '"Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[[GFut.Application.ViewModels.PersonViewModel, GFut.Application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"'. (8a1b66c8)
2019-09-17T18:16:22.3490821+01:00 0HLPRIAKCIC7F:00000003 [INF] Executed action "GFut.Services.Api.Controllers.PersonController.Get (GFut.Services.Api)" in 35908.3802ms (afa2e885)
2019-09-17T18:16:22.7847316+01:00 0HLPRIAKCIC7F:00000003 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): O sistema não pode encontrar o arquivo especificado
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.WriteObject(TextWriter writer, Object value)
   at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.<WriteResponseBodyAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__28`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultFilters>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:2,State:0,Class:20
2019-09-17T18:16:22.9058595+01:00 0HLPRIAKCIC7F:00000003 [WRN] The response has already started, the error page middleware will not be executed. (e1dd4c0d)
2019-09-17T18:16:23.4087594+01:00 0HLPRIAKCIC7F:00000003 [ERR] Connection id ""0HLPRIAKCIC7F"", Request id ""0HLPRIAKCIC7F:00000003"": An unhandled exception was thrown by the application. (560e7d32)
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): O sistema não pode encontrar o arquivo especificado
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.WriteObject(TextWriter writer, Object value)
   at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.<WriteResponseBodyAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__28`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultFilters>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:2,State:0,Class:20
2019-09-17T18:16:23.5254502+01:00 0HLPRIAKCIC7F:00000003 [INF] Request finished in 37144.3229ms 200 application/json; charset=utf-8 (791a596a)
2019-09-17T19:31:40.6723492+01:00 0HLPRJL42EBSN:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:51933/api/person   (ca22a1cb)
2019-09-17T19:31:42.0306771+01:00 0HLPRJL42EBSN:00000001 [INF] Route matched with "{action = \"Get\", controller = \"Person\"}". Executing action "GFut.Services.Api.Controllers.PersonController.Get (GFut.Services.Api)" (a44c0341)
2019-09-17T19:31:46.2089673+01:00 0HLPRJL42EBSN:00000001 [INF] Executing action method "GFut.Services.Api.Controllers.PersonController.Get (GFut.Services.Api)" - Validation state: Valid (dad538d7)
2019-09-17T19:31:46.4349202+01:00 0HLPRJL42EBSN:00000001 [INF] Executed action method "GFut.Services.Api.Controllers.PersonController.Get (GFut.Services.Api)", returned result "Microsoft.AspNetCore.Mvc.ObjectResult" in 113.898ms. (50a9e262)
2019-09-17T19:31:46.5398127+01:00 0HLPRJL42EBSN:00000001 [INF] Executing ObjectResult, writing value of type '"Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[[GFut.Application.ViewModels.PersonViewModel, GFut.Application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"'. (8a1b66c8)
2019-09-17T19:31:49.7213415+01:00 0HLPRJL42EBSN:00000001 [INF] Executed action "GFut.Services.Api.Controllers.PersonController.Get (GFut.Services.Api)" in 7657.0545ms (afa2e885)
2019-09-17T19:31:50.2354364+01:00 0HLPRJL42EBSN:00000001 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Person'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.WriteObject(TextWriter writer, Object value)
   at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.<WriteResponseBodyAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__28`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultFilters>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
ClientConnectionId:fb0b8708-14d8-402b-b215-a3e55afba9fc
Error Number:208,State:1,Class:16
2019-09-17T19:31:50.3343933+01:00 0HLPRJL42EBSN:00000001 [WRN] The response has already started, the error page middleware will not be executed. (e1dd4c0d)
2019-09-17T19:31:50.7541345+01:00 0HLPRJL42EBSN:00000001 [ERR] Connection id ""0HLPRJL42EBSN"", Request id ""0HLPRJL42EBSN:00000001"": An unhandled exception was thrown by the application. (560e7d32)
System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Person'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.WriteObject(TextWriter writer, Object value)
   at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.<WriteResponseBodyAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__28`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultFilters>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
ClientConnectionId:fb0b8708-14d8-402b-b215-a3e55afba9fc
Error Number:208,State:1,Class:16
2019-09-17T19:31:51.0356989+01:00 0HLPRJL42EBSN:00000001 [INF] Request finished in 10507.5671ms 200 application/json; charset=utf-8 (791a596a)
